### ISSUE TITLE
Failed ECS deployment feedback

### ISSUE THREAD

**Issue by huewood** [buildkite-plugins/ecs-deploy-buildkite-plugin#109]
Would it be possible to return **specific** feedback from ECS in the case that the task failed to launch (i.e. could not find image, etc)?

When running a service update that fails, the logs will return `Service failed to deploy` (image attached).
![image](https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin/assets/32667373/6235c8bc-d5ee-4c99-9bdb-855e277f9c27)

Having this directly in the Buildkite logs would be very handy as it may negate needing to go into the AWS console & dig around as to why the deployment failed.

**Comment by toote** [comment]
@huewood that is quite an interesting idea... unfortunately, I don't think it would be possible for two reasons.

1- there are a lot of reasons why a deployment may fail. Off the top of my head I can think of: wrong image (or lack of permissions), healthchecks - both in the container or target group -, and rollback configurations in the deployment. So the places to look at are very environment-dependent and normally outside of ECS itself (for example, in my experience, you need to read task logs to debug healthcheck failures)
2- even if we had a complete list of things to look at, getting all that information will mean giving the agent a whole lot of permissions to be able to gather the information which may be a deal-breaker in a lot of situations
