### ISSUE TITLE
Message in readme about service must be created

### ISSUE THREAD

**Issue by toolmantim** [buildkite-plugins/ecs-deploy-buildkite-plugin#35]
In the readme we have `The ECS service must have been created before using this plugin.` but this doesn't seem to be true 🤔

**Comment by hklo** [comment]
It seem that it will create the service if it not found
https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin/blob/master/hooks/command#L28

**Comment by toote** [comment]
This was fixed in https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin/pull/36/commits/b58d72f322fd2f19a4a90daa79593b14924755fa
