### ISSUE TITLE
Plugin development status; support for rollback and rollout strategies 

### ISSUE THREAD

**Issue by scadu** [buildkite-plugins/ecs-deploy-buildkite-plugin#72]
Hi 👋 

We've just started exploring Buildkite and I wonder if there's a roadmap available somewhere?
I am wondering if you plan to add more features to the plugin like rollback (on top of what ECS provides when the service rollout fails) and rollout strategies?

**Comment by jradtilbrook** [comment]
Hey @scadu, @pzeballos maintains this repo so might be able to provide a bit more details but in general we don't have a roadmap for plugins and I don't believe we do for this plugin at the moment.

We accept PRs from the community to add new features they would find useful though so if there is anything in particular you'd like please open a PR. Or if you don't have time or expertise, opening an issue explaining the feature is helpful for the team to evaluate it and prioritise working on something

**Comment by pzeballos** [comment]
Hey @scadu! Thanks for reaching out! As Jarryd mentioned, we don't have a roadmap available for plugins, we would love to do that, but we don't have the capacity at the moment. 
We are not adding new functionalities, but if there is something you are interested you are welcome to create a PR, and we'll take a look so we can add it 🙂 Thanks!
